---
title: Project title
author: by Team name
output: github_document
---

## Summary

Write-up of your project and findings go here. 
Think of this as the text of your presentation. 
The length should be roughly 5 minutes when read out loud.
Although pacing varies, a 5-minute speech is roughly 750 words. 
To use the word count addin, select the text you want to count the words of (probably this is the 
Summary section of this document, go to Addins, and select the `Word count` addin).
This addin counts words using two different algorithms, but the results should be similar and as long as you're in the ballpark of 750 words, you're good! 
The addin will ignore code chunks and only count the words in prose.

You can also load your data here and present any analysis results / plots, but I strongly urge you to keep that to a minimum (maybe only the most important graphic, if you have one you can choose). 
And make sure to hide your code with  `echo = FALSE` unless the point you are trying to make is about the code itself.
Your results with proper output and graphics go in your presentation, this space is for a brief summary of your project.

```{r load-data, echo = FALSE}
Weight_Issues <- read.csv(here::here("data/Weight Issues.csv"))
Substance_Abuse <- read.csv(here::here("data/Substance Abuse.csv"))
```

## Presentation

Our presentation can be found https://f2209927ca3c49c386c7f1f6717e6018.app.rstudio.cloud/file_show?path=%2Fcloud%2Fproject%2Fpresentation%2Freveal.js_template%2Fpresentation.html]

## Data 

Centers for Disease Control and Prevention 2019, *DASH YRBSS - Weight Control (MS), DASH - Youth Risk Behavior Surveillance System (YRBSS): Middle School* DASH Public Inquiries, viewed 22 October 2021, data file(CSV), <https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-YRBSS-Weight-Control-MS-/xg5u-askg>

Centers for Disease Control and Prevention 2019, *DASH YRBSS - Alcohol and Other Drug Use (MS), DASH - Youth Risk Behavior Surveillance System (YRBSS): Middle School* DASH Public Inquiries, viewed 22 October 2021, data file(CSV), <https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-YRBSS-Alcohol-and-Other-Drug-Use-MS-/bdg5-rnzz>
## References

#References 

Data Set (Substance Abuse): https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-YRBSS-Alcohol-and-Other-Drug-Use-MS-/bdg5-rnzz,

Data Set (Weight Issues): https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-YRBSS-Weight-Control-MS-/xg5u-askg,
